### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by fnbory** [sagieppel/Generator-evaluator-selector-net-a-modular-approach-for-panoptic-segmentation#2]
hi,Thank you for your great work, great ideas. I downloaded the dataset (2017 Panoptic Train/Val annotations [821MB]),     but the image doesn't seem to match. I want to know if you are using this dataset?
 It seems that only one of datasets in the official online sites is about panoptic.so..I am comfused about this

**Comment by sagieppel** [comment]
The images are the  2017 train/val images http://cocodataset.org/#download

**Comment by fnbory** [comment]
Yeah! thanks for your reply,It works now!
